# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(815, 447)
        Dialog.setStyleSheet("QDialog{\n"
"    background:rgba(255, 255, 255);\n"
"    \n"
"}")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(40, 250, 371, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setEnabled(True)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 86, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setEnabled(True)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 20, 251, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 10, 371, 221))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setEnabled(True)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 354, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 60, 169, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 96, 169, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 130, 169, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 160, 169, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 71, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(70, 58, 71, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(70, 92, 71, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(70, 126, 41, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.mqtt2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.mqtt2.setEnabled(True)
        self.mqtt2.setGeometry(QtCore.QRect(110, 90, 209, 20))
        self.mqtt2.setObjectName("mqtt2")
        self.mqtt5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.mqtt5.setEnabled(True)
        self.mqtt5.setGeometry(QtCore.QRect(110, 180, 209, 20))
        self.mqtt5.setObjectName("mqtt5")
        self.mqtt4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.mqtt4.setEnabled(True)
        self.mqtt4.setGeometry(QtCore.QRect(110, 150, 209, 20))
        self.mqtt4.setObjectName("mqtt4")
        self.mqtt3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.mqtt3.setEnabled(True)
        self.mqtt3.setGeometry(QtCore.QRect(110, 120, 209, 20))
        self.mqtt3.setObjectName("mqtt3")
        self.mqtt1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.mqtt1.setEnabled(True)
        self.mqtt1.setGeometry(QtCore.QRect(110, 60, 209, 20))
        self.mqtt1.setObjectName("mqtt1")
        self.mqtt11_2 = QtWidgets.QLabel(self.groupBox_2)
        self.mqtt11_2.setEnabled(True)
        self.mqtt11_2.setGeometry(QtCore.QRect(40, 58, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mqtt11_2.setFont(font)
        self.mqtt11_2.setObjectName("mqtt11_2")
        self.mqtt44_2 = QtWidgets.QLabel(self.groupBox_2)
        self.mqtt44_2.setEnabled(True)
        self.mqtt44_2.setGeometry(QtCore.QRect(40, 149, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mqtt44_2.setFont(font)
        self.mqtt44_2.setObjectName("mqtt44_2")
        self.mqtt55_2 = QtWidgets.QLabel(self.groupBox_2)
        self.mqtt55_2.setEnabled(True)
        self.mqtt55_2.setGeometry(QtCore.QRect(40, 179, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mqtt55_2.setFont(font)
        self.mqtt55_2.setObjectName("mqtt55_2")
        self.mqtt22_2 = QtWidgets.QLabel(self.groupBox_2)
        self.mqtt22_2.setEnabled(True)
        self.mqtt22_2.setGeometry(QtCore.QRect(40, 88, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mqtt22_2.setFont(font)
        self.mqtt22_2.setObjectName("mqtt22_2")
        self.mqtt33_2 = QtWidgets.QLabel(self.groupBox_2)
        self.mqtt33_2.setEnabled(True)
        self.mqtt33_2.setGeometry(QtCore.QRect(40, 118, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mqtt33_2.setFont(font)
        self.mqtt33_2.setObjectName("mqtt33_2")
        self.comlb = QtWidgets.QLabel(self.groupBox_2)
        self.comlb.setEnabled(True)
        self.comlb.setGeometry(QtCore.QRect(100, 71, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comlb.setFont(font)
        self.comlb.setObjectName("comlb")
        self.botelvlb = QtWidgets.QLabel(self.groupBox_2)
        self.botelvlb.setEnabled(True)
        self.botelvlb.setGeometry(QtCore.QRect(100, 101, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botelvlb.setFont(font)
        self.botelvlb.setObjectName("botelvlb")
        self.comboBox_com = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_com.setGeometry(QtCore.QRect(180, 68, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_com.setFont(font)
        self.comboBox_com.setEditable(True)
        self.comboBox_com.setObjectName("comboBox_com")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_botelv = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_botelv.setGeometry(QtCore.QRect(180, 98, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_botelv.setFont(font)
        self.comboBox_botelv.setEditable(True)
        self.comboBox_botelv.setObjectName("comboBox_botelv")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_botelv.addItem("")
        self.comboBox_timeout = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_timeout.setGeometry(QtCore.QRect(180, 128, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_timeout.setFont(font)
        self.comboBox_timeout.setEditable(True)
        self.comboBox_timeout.setObjectName("comboBox_timeout")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.comboBox_timeout.addItem("")
        self.timeoutlb = QtWidgets.QLabel(self.groupBox_2)
        self.timeoutlb.setEnabled(True)
        self.timeoutlb.setGeometry(QtCore.QRect(100, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeoutlb.setFont(font)
        self.timeoutlb.setObjectName("timeoutlb")
        self.loglb = QtWidgets.QLabel(self.groupBox_2)
        self.loglb.setEnabled(True)
        self.loglb.setGeometry(QtCore.QRect(40, 100, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loglb.setFont(font)
        self.loglb.setObjectName("loglb")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setEnabled(True)
        self.splitter_2.setGeometry(QtCore.QRect(79, 69, 71, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_5.setEnabled(True)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setGeometry(QtCore.QRect(110, 400, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setGeometry(QtCore.QRect(250, 400, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.close_btn.setObjectName("close_btn")
        self.auto_btn = QtWidgets.QPushButton(Dialog)
        self.auto_btn.setGeometry(QtCore.QRect(420, 220, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.auto_btn.setFont(font)
        self.auto_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.auto_btn.setObjectName("auto_btn")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 10, 351, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(70, 20, 89, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 20, 89, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QtCore.QRect(100, 60, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(100, 90, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(70, 140, 51, 111))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(130, 140, 181, 111))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_6.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_6.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_15.setEnabled(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_6.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_6.addWidget(self.lineEdit_16)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(70, 270, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_program = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_program.setGeometry(QtCore.QRect(150, 270, 141, 22))
        self.comboBox_program.setEditable(True)
        self.comboBox_program.setObjectName("comboBox_program")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(30, 322, 71, 20))
        self.label_11.setObjectName("label_11")
        self.num_lb = QtWidgets.QLabel(self.groupBox_3)
        self.num_lb.setGeometry(QtCore.QRect(110, 322, 54, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.num_lb.setFont(font)
        self.num_lb.setObjectName("num_lb")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 110, 71, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.auto_btn_2 = QtWidgets.QPushButton(Dialog)
        self.auto_btn_2.setGeometry(QtCore.QRect(420, 180, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.auto_btn_2.setFont(font)
        self.auto_btn_2.setStatusTip("")
        self.auto_btn_2.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.auto_btn_2.setObjectName("auto_btn_2")
        self.run_btn = QtWidgets.QPushButton(Dialog)
        self.run_btn.setGeometry(QtCore.QRect(520, 400, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.run_btn.setObjectName("run_btn")
        self.stop_btn = QtWidgets.QPushButton(Dialog)
        self.stop_btn.setGeometry(QtCore.QRect(640, 400, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.stop_btn.setObjectName("stop_btn")
        self.auto_btn_3 = QtWidgets.QPushButton(Dialog)
        self.auto_btn_3.setGeometry(QtCore.QRect(770, 420, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.auto_btn_3.setFont(font)
        self.auto_btn_3.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.auto_btn_3.setObjectName("auto_btn_3")
        self.auto_btn_4 = QtWidgets.QPushButton(Dialog)
        self.auto_btn_4.setEnabled(True)
        self.auto_btn_4.setGeometry(QtCore.QRect(740, 420, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.auto_btn_4.setFont(font)
        self.auto_btn_4.setStyleSheet("QPushButton{\n"
"\n"
"    background:rgba(255, 255, 255,100);\n"
"    color:rgb(85, 170, 255);\n"
"}")
        self.auto_btn_4.setObjectName("auto_btn_4")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(40, 450, 761, 101))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        self.comboBox_com.setCurrentIndex(2)
        self.comboBox_botelv.setCurrentIndex(3)
        self.comboBox_timeout.setCurrentIndex(2)
        self.radioButton.clicked['bool'].connect(self.lineEdit_9.setDisabled)
        self.radioButton.clicked['bool'].connect(self.lineEdit_8.setEnabled)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_8.setDisabled)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_9.setEnabled)
        self.auto_btn.clicked.connect(self.auto_btn.hide)
        self.auto_btn.clicked.connect(self.auto_btn_2.show)
        self.auto_btn_2.clicked.connect(self.auto_btn_2.hide)
        self.auto_btn_2.clicked.connect(self.auto_btn.show)
        self.auto_btn_4.clicked.connect(self.auto_btn_4.hide)
        self.auto_btn_3.clicked.connect(self.auto_btn_3.hide)
        self.auto_btn_4.clicked.connect(self.auto_btn_3.show)
        self.auto_btn_3.clicked.connect(self.auto_btn_4.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.Dialog=Dialog

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data source"))
        self.groupBox.setTitle(_translate("Dialog", "設備三元組"))
        self.label.setText(_translate("Dialog", "Produckey"))
        self.label_2.setText(_translate("Dialog", "Devicename"))
        self.label_3.setText(_translate("Dialog", "Devicesecret"))
        self.groupBox_2.setTitle(_translate("Dialog", "通信方式"))
        self.pushButton.setText(_translate("Dialog", "串口"))
        self.pushButton_2.setText(_translate("Dialog", "Database"))
        self.pushButton_3.setText(_translate("Dialog", "MQTT"))
        self.label_4.setText(_translate("Dialog", "table"))
        self.label_5.setText(_translate("Dialog", "Host"))
        self.label_6.setText(_translate("Dialog", "Port"))
        self.label_7.setText(_translate("Dialog", "DB"))
        self.mqtt11_2.setText(_translate("Dialog", "Broker"))
        self.mqtt44_2.setText(_translate("Dialog", "Keepalive"))
        self.mqtt55_2.setText(_translate("Dialog", "Topic"))
        self.mqtt22_2.setText(_translate("Dialog", "Port"))
        self.mqtt33_2.setText(_translate("Dialog", "ClientID"))
        self.comlb.setText(_translate("Dialog", "端口號"))
        self.botelvlb.setText(_translate("Dialog", "波特率"))
        self.comboBox_com.setItemText(0, _translate("Dialog", "COM1"))
        self.comboBox_com.setItemText(1, _translate("Dialog", "COM2"))
        self.comboBox_com.setItemText(2, _translate("Dialog", "COM3"))
        self.comboBox_com.setItemText(3, _translate("Dialog", "COM4"))
        self.comboBox_com.setItemText(4, _translate("Dialog", "COM5"))
        self.comboBox_com.setItemText(5, _translate("Dialog", "COM6"))
        self.comboBox_com.setItemText(6, _translate("Dialog", "COM7"))
        self.comboBox_com.setItemText(7, _translate("Dialog", "COM8"))
        self.comboBox_com.setItemText(8, _translate("Dialog", "COM9"))
        self.comboBox_com.setItemText(9, _translate("Dialog", "COM10"))
        self.comboBox_botelv.setItemText(0, _translate("Dialog", "1200"))
        self.comboBox_botelv.setItemText(1, _translate("Dialog", "2400"))
        self.comboBox_botelv.setItemText(2, _translate("Dialog", "4800"))
        self.comboBox_botelv.setItemText(3, _translate("Dialog", "9600"))
        self.comboBox_botelv.setItemText(4, _translate("Dialog", "19200"))
        self.comboBox_botelv.setItemText(5, _translate("Dialog", "38400"))
        self.comboBox_timeout.setItemText(0, _translate("Dialog", "0.1"))
        self.comboBox_timeout.setItemText(1, _translate("Dialog", "0.2"))
        self.comboBox_timeout.setItemText(2, _translate("Dialog", "0.3"))
        self.comboBox_timeout.setItemText(3, _translate("Dialog", "0.4"))
        self.comboBox_timeout.setItemText(4, _translate("Dialog", "0.5"))
        self.comboBox_timeout.setItemText(5, _translate("Dialog", "0.6"))
        self.comboBox_timeout.setItemText(6, _translate("Dialog", "0.7"))
        self.comboBox_timeout.setItemText(7, _translate("Dialog", "0.8"))
        self.comboBox_timeout.setItemText(8, _translate("Dialog", "0.9"))
        self.comboBox_timeout.setItemText(9, _translate("Dialog", "1.0"))
        self.timeoutlb.setText(_translate("Dialog", "timeout"))
        self.loglb.setText(_translate("Dialog", "Please Choice one Singel Source"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.close_btn.setText(_translate("Dialog", "Close"))
        self.auto_btn.setToolTip(_translate("Dialog", "show"))
        self.auto_btn.setText(_translate("Dialog", "→"))
        self.groupBox_3.setTitle(_translate("Dialog", "Model"))
        self.radioButton.setText(_translate("Dialog", "Proxy"))
        self.radioButton_2.setText(_translate("Dialog", "Server"))
        self.label_8.setText(_translate("Dialog", " ProxyURL"))
        self.label_9.setText(_translate("Dialog", "ServerURL"))
        self.lineEdit_8.setText(_translate("Dialog", "http://10.132.37.177:8088/auth/device/"))
        self.lineEdit_9.setText(_translate("Dialog", "https://service-o8bikfta-1256676747.ap-guangzhou.apigateway.myqcloud.com/release/corepro_deviceauth/mqtt_auth?X-MicroService-Name=beacon-corepro-deviceauth&X-NameSpace-Code=default-code"))
        self.label_13.setText(_translate("Dialog", "iotHost"))
        self.label_14.setText(_translate("Dialog", "iotPost"))
        self.label_15.setText(_translate("Dialog", "iotId"))
        self.label_16.setText(_translate("Dialog", "iotToken"))
        self.label_10.setText(_translate("Dialog", "計算程式"))
        self.label_11.setText(_translate("Dialog", "發送消息數："))
        self.num_lb.setText(_translate("Dialog", "0"))
        self.pushButton_4.setText(_translate("Dialog", "鑒 權"))
        self.auto_btn_2.setToolTip(_translate("Dialog", "hide"))
        self.auto_btn_2.setText(_translate("Dialog", "←"))
        self.run_btn.setText(_translate("Dialog", "Run"))
        self.stop_btn.setText(_translate("Dialog", "Stop"))
        self.auto_btn_3.setToolTip(_translate("Dialog", "show"))
        self.auto_btn_3.setText(_translate("Dialog", "↓"))
        self.auto_btn_4.setToolTip(_translate("Dialog", "hide"))
        self.auto_btn_4.setText(_translate("Dialog", "↑"))

